### PR TITLE
Initializing a ReactJS application

### PR DESCRIPTION
**Pull request by avikalpg**
## Proposal
We can create this application as a ReactJS application which does the following:
1. takes the GitHub username as an input (with an option to choose the year for which they want the skyline)
2. fetches the activity of the user using the GitHub API using `axios`
3. renders the skyline (initially in 2D, and ideally in 3D)

There doesn't seem to be any reason for using a server-side rendered application for this (the original skyline.github.com is written in NuxtJS).

Since this would generate a static SPA, we can host this as a GitHub page.

### CODE REVIEW

**Comment by ToasterUwU** [comment]
For me its important that i can export the 3D Skyline as a STL or another format that I can use for 3D printing it. That was the main point for me with the Skyline.

**Comment by ftrauernicht** [comment]
> For me its important that i can export the 3D Skyline as a STL or another format that I can use for 3D printing it. That was the main point for me with the Skyline.
> 

Same here. The 2D graph is easily accessiable via the Profile Page

**Comment by thedocruby** [comment]
I'd argue that a render is a good place to start. That serves the purpose for many people, and gives you a foundation to build on, so you can work your way up to features like STL export

I recently started a project, and I had to delete much of the code to focus on a foundation first, instead of having to refactor every aspect when i wanted to make a structural change. Starting with a good foundation saves time and often gives you higher quality in the end.

**Comment by avikalpg** [comment]
Surely, the primary aim is to be able to get the 3D Skyline.

**Pull request merged**
